version: '3'
services:
  wtbbot:
      container_name: wtbbot
      build:
        context: .
        dockerfile: ./docker/wtbbot/Dockerfile
      ports:
        - 9090:9090
      restart: always
      environment:
        REDIS_ADDR: wtbbot-redis:6379
        TOKEN: $TOKEN
        WEBHOOKURL: $WEBHOOKURL
        TLSKEY: $TLSKEY
        TLSCERT: $TLSCERT
        TIMEOUT_SECONDS: $TIMEOUT_SECONDS
  redis:
      image: redis:6.2.6-alpine3.14
      container_name: wtbbot-redis
